site_name: Estrutura de Dados 2

theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  palette:
    - scheme: default 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Modo Escuro
      primary: white
      accent: #8ECDDD
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Modo Claro  
      primary: black
      accent: #8ECDDD
  #favicon: assets/favicon.ico
  #logo: assets/favicon.ico

  font:
    text: Roboto
  language: pt
  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - navigation.tabs.sticky

nav:
  - Ínicio: index.md
  - Anotações: 
    - Tabela de Dispersão: conteudos/tabela_de_dispersao.md
    - Busca: conteudos/busca.md
    - QuickSelect: conteudos/quickselect.md
    - QuickSort: conteudos/quicksort.md